"""Description of changes

Revision ID: 477d295c012e
Revises: 0a45c627e276
Create Date: 2024-08-04 21:20:41.976405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477d295c012e'
down_revision = '0a45c627e276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_comments_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_timestamp'))
        batch_op.drop_index(batch_op.f('ix_comments_email'))

    op.drop_table('comments')
    # ### end Alembic commands ###
